# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\..\ui\user_load_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_testRunWindow(object):
    def setupUi(self, testRunWindow):
        testRunWindow.setObjectName("testRunWindow")
        testRunWindow.resize(1114, 685)
        self.centralwidget = QtWidgets.QWidget(testRunWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.treeWidget = QtWidgets.QTreeWidget(self.layoutWidget)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.horizontalLayout_2.addWidget(self.treeWidget)
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(self.layoutWidget)
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.horizontalLayout_2.addWidget(self.verticalScrollBar_2)
        self.verticalScrollBar_2.raise_()
        self.treeWidget.raise_()
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.layoutWidget1)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.horizontalLayout.addWidget(self.verticalScrollBar)
        self.verticalLayout.addWidget(self.splitter)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        testRunWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(testRunWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1114, 26))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        testRunWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(testRunWindow)
        self.statusbar.setObjectName("statusbar")
        testRunWindow.setStatusBar(self.statusbar)
        self.action_Open = QtWidgets.QAction(testRunWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_Save = QtWidgets.QAction(testRunWindow)
        self.action_Save.setObjectName("action_Save")
        self.actionLog_Location = QtWidgets.QAction(testRunWindow)
        self.actionLog_Location.setObjectName("actionLog_Location")
        self.actionExit = QtWidgets.QAction(testRunWindow)
        self.actionExit.setObjectName("actionExit")
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.action_Save)
        self.menu_File.addAction(self.actionExit)
        self.menuSettings.addAction(self.actionLog_Location)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(testRunWindow)
        QtCore.QMetaObject.connectSlotsByName(testRunWindow)

    def retranslateUi(self, testRunWindow):
        _translate = QtCore.QCoreApplication.translate
        testRunWindow.setWindowTitle(_translate("testRunWindow", "User Load Test"))
        self.menu_File.setTitle(_translate("testRunWindow", "&File"))
        self.menuSettings.setTitle(_translate("testRunWindow", "Settings"))
        self.action_Open.setText(_translate("testRunWindow", "&Open"))
        self.action_Save.setText(_translate("testRunWindow", "&Save"))
        self.actionLog_Location.setText(_translate("testRunWindow", "Log Location"))
        self.actionExit.setText(_translate("testRunWindow", "Exit"))
